import {
  reportsScenarioSchema,
  type ReportsScenario,
} from '../fixtures/schemas'
import {
  makeReportDetail,
  makeReportListItem,
  makeUser,
} from '../fixtures/builders'

export const baseReportsScenario = reportsScenarioSchema.parse({
  user: makeUser(),
  reports: [
    makeReportListItem({
      id: 'report-1003',
      startedAt: '2026-04-09T21:44:00-05:00',
      completedAt: '2026-04-09T22:15:00-05:00',
      bottleCount: 18,
      locationName: 'Main Bar',
      status: 'reviewed',
    }),
    makeReportListItem({
      id: 'report-1002',
      status: 'unreviewed',
      startedAt: '2026-04-10T18:04:00-05:00',
      completedAt: '2026-04-10T18:29:00-05:00',
      bottleCount: 11,
      locationName: 'Patio Bar',
      userId: 'user-staff-1',
      userDisplayName: 'Morgan Lee',
    }),
    makeReportListItem({
      id: 'report-1001',
      status: 'processing',
      startedAt: '2026-04-11T16:12:00-05:00',
      completedAt: undefined,
      bottleCount: 9,
      locationName: 'Backstock',
    }),
    makeReportListItem({
      id: 'report-1000',
      status: 'created',
      startedAt: '2026-04-11T18:44:00-05:00',
      completedAt: undefined,
      bottleCount: 6,
      locationName: 'Private Room',
    }),
  ],
  details: {
    'report-1003': makeReportDetail({
      id: 'report-1003',
      status: 'reviewed',
      bottleRecords: [
        {
          id: 'record-reviewed-1',
          bottleId: 'bottle-1',
          imageUrl: '/fixtures/report-bottle-clear.svg',
          bottleName: "Tito's Handmade Vodka",
          category: 'Vodka',
          upc: '619947000013',
          volumeMl: 750,
          fillPercent: 62,
          corrected: false,
          status: 'reviewed',
        },
        {
          id: 'record-reviewed-2',
          bottleId: 'bottle-2',
          imageUrl: '/fixtures/report-bottle-amber.svg',
          bottleName: 'Espolòn Blanco',
          category: 'Tequila',
          upc: '080686834203',
          volumeMl: 750,
          fillPercent: 28,
          corrected: true,
          status: 'reviewed',
          originalModelOutput: {
            bottleName: 'Espolon Silver',
            fillPercent: 41,
          },
          correctedValues: {
            bottleName: 'Espolòn Blanco',
            fillPercent: 28,
          },
        },
      ],
    }),
    'report-1002': makeReportDetail({
      id: 'report-1002',
      status: 'unreviewed',
      startedAt: '2026-04-10T18:04:00-05:00',
      completedAt: '2026-04-10T18:29:00-05:00',
      userId: 'user-staff-1',
      userDisplayName: 'Morgan Lee',
      bottleRecords: [
        {
          id: 'record-unreviewed-1',
          bottleId: 'bottle-3',
          imageUrl: '/fixtures/report-bottle-clear.svg',
          bottleName: 'Montelobos Mezcal',
          category: 'Mezcal',
          upc: '618115630028',
          volumeMl: 750,
          fillPercent: 50,
          corrected: false,
          status: 'inferred',
          originalModelOutput: {
            bottleName: 'Montelobos Mezcal',
            fillPercent: 50,
          },
        },
        {
          id: 'record-unreviewed-2',
          imageUrl: '/fixtures/report-bottle-ruby.svg',
          bottleName: 'Unknown bottle',
          category: undefined,
          upc: undefined,
          volumeMl: undefined,
          fillPercent: 0,
          corrected: false,
          status: 'failed',
          errorCode: 'catalog_no_match',
          errorMessage: 'The capture could not be matched to a catalog bottle.',
        },
      ],
    }),
    'report-1001': makeReportDetail({
      id: 'report-1001',
      status: 'processing',
      startedAt: '2026-04-11T16:12:00-05:00',
      completedAt: undefined,
      bottleRecords: [
        {
          id: 'record-processing-1',
          bottleId: 'bottle-4',
          imageUrl: '/fixtures/report-bottle-amber.svg',
          bottleName: 'Wild Turkey 101',
          category: 'Bourbon',
          upc: '072105900151',
          volumeMl: 1000,
          fillPercent: 70,
          corrected: false,
          status: 'inferred',
          originalModelOutput: {
            bottleName: 'Wild Turkey 101',
            fillPercent: 70,
          },
        },
        {
          id: 'record-processing-2',
          imageUrl: '/fixtures/report-bottle-clear.svg',
          bottleName: 'Pending bottle',
          category: undefined,
          upc: undefined,
          volumeMl: undefined,
          fillPercent: 0,
          corrected: false,
          status: 'pending',
        },
        {
          id: 'record-processing-3',
          imageUrl: '/fixtures/report-bottle-ruby.svg',
          bottleName: 'Unreadable label',
          category: undefined,
          upc: undefined,
          volumeMl: undefined,
          fillPercent: 0,
          corrected: false,
          status: 'failed',
          errorCode: 'image_unreadable',
          errorMessage: 'The label could not be read clearly enough to infer a bottle.',
        },
      ],
    }),
    'report-1000': makeReportDetail({
      id: 'report-1000',
      status: 'created',
      startedAt: '2026-04-11T18:44:00-05:00',
      completedAt: undefined,
      bottleRecords: [
        {
          id: 'record-created-1',
          imageUrl: '/fixtures/report-bottle-clear.svg',
          bottleName: 'Awaiting processing',
          category: undefined,
          upc: undefined,
          volumeMl: undefined,
          fillPercent: 0,
          corrected: false,
          status: 'pending',
        },
        {
          id: 'record-created-2',
          imageUrl: '/fixtures/report-bottle-amber.svg',
          bottleName: 'Awaiting processing',
          category: undefined,
          upc: undefined,
          volumeMl: undefined,
          fillPercent: 0,
          corrected: false,
          status: 'pending',
        },
      ],
    }),
    'report-missing-media': makeReportDetail({
      id: 'report-missing-media',
      status: 'reviewed',
      bottleRecords: [
        {
          id: 'record-missing',
          imageUrl: '',
          bottleName: 'Campari',
          category: 'Aperitif',
          upc: '721059000101',
          volumeMl: 750,
          fillPercent: 16,
          corrected: false,
          status: 'reviewed',
        },
      ],
    }),
  },
}) satisfies ReportsScenario
