export const dashboardTokens = {
  fonts: {
    display: 'var(--font-display)',
    body: 'var(--font-body)',
    label: 'var(--font-label)',
  },
  colors: {
    bgApp: 'var(--color-bg-app)',
    bgCanvas: 'var(--color-bg-canvas)',
    surfaceLow: 'var(--color-surface-low)',
    surfaceBase: 'var(--color-surface-base)',
    surfaceHigh: 'var(--color-surface-high)',
    surfaceHighest: 'var(--color-surface-highest)',
    surfaceVariant: 'var(--color-surface-variant)',
    borderStrong: 'var(--color-border-strong)',
    borderSubtle: 'var(--color-border-subtle)',
    textPrimary: 'var(--color-text-primary)',
    textSecondary: 'var(--color-text-secondary)',
    textMuted: 'var(--color-text-muted)',
    accentSoft: 'var(--color-accent-soft)',
    accent: 'var(--color-accent)',
    accentStrong: 'var(--color-accent-strong)',
    accentInk: 'var(--color-accent-ink)',
    success: 'var(--color-success)',
    successStrong: 'var(--color-success-strong)',
    error: 'var(--color-error)',
    errorStrong: 'var(--color-error-strong)',
  },
  spacing: {
    xs: 'var(--space-xs)',
    sm: 'var(--space-sm)',
    md: 'var(--space-md)',
    lg: 'var(--space-lg)',
    xl: 'var(--space-xl)',
    x2: 'var(--space-2xl)',
    x3: 'var(--space-3xl)',
    x4: 'var(--space-4xl)',
    x5: 'var(--space-5xl)',
    x6: 'var(--space-6xl)',
  },
  radii: {
    sm: 'var(--radius-sm)',
    md: 'var(--radius-md)',
    lg: 'var(--radius-lg)',
    xl: 'var(--radius-xl)',
    full: 'var(--radius-full)',
  },
  shadows: {
    ambient: 'var(--shadow-ambient)',
  },
} as const
